# For starting Homekit - 1
  - alias: 'Start HomeKit when media_player ready'
    trigger:
      #- platform: event
      #  event_type: media_player.network_ready
      - platform: event
        event_type: media_player.network_complete
      #- platform: event
      #  event_type: media_player.network_complete_some_dead
    action:
      - service: homekit.start
# For starting Homekit - 2
  - alias: 'Start HomeKit'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:05  # Waits 5 minutes
      - service: homekit.start
# Hue remote 1 hold
  - alias: 'Hold Hue On Button -> Time For Bed'
    trigger:
      - platform: state
        entity_id: sensor.hue_dimmer_switch_1
        to: '1_hold'
    action:
      service: script.turn_on
      entity_id: script.time_for_bed
# Hue remote 4 hold
  - alias: 'Hold Hue Off Button -> Goodnight'
    trigger:
      - platform: state
        entity_id: sensor.hue_dimmer_switch_1
        to: '4_hold'
    action:
      service: script.turn_on
      entity_id: script.goodnight
# Hue remote 2 hold
  - alias: 'Hold Hue Dim Up Button -> Spotify to Bedroom'
    trigger:
      - platform: state
        entity_id: sensor.hue_dimmer_switch_1
        to: '2_hold'
    action:
      - service: script.turn_on
        entity_id: script.spotify_bedroom
# Disarms and turns on Media Player automations if any person arrives
  - alias: 'Any Entry -> Good Morning'
    trigger:
      - platform: state
        entity_id: device_tracker.iphone
        to: 'home'
      - platform: state
        entity_id: device_tracker.meghans_iphone
        to: 'home'
      - platform: event
        event_type: abode_automation
        event_data:
          device_name: 'Any phone enters -> Standby mode'
    action:
      - service: script.turn_on
        entity_id: script.good_morning
# Turns alarm to Standby if 5:30am and someone home
# (Standby is redundant with Abode, but it also turns on media autos)
  - alias: '5:30 AM At Home -> Good Morning'
    trigger:
      - platform: time
        at: '05:30:00'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      - service: script.turn_on
        entity_id: script.good_morning
# Turns alarm to Home if 11:00pm and someone home
# (Redundant with Abode, but M's GPS is sometimes bad)
  - alias: '11 PM At Home -> Home'
    trigger:
      - platform: time
        at: '23:00:00'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.abode
# Turns on Front Door light if anyone gets home after sunset. Turns off after 5 minutes
  - alias: 'Any Entry After Sunset -> Porch On Then Off'
    trigger:
      - platform: state
        entity_id: device_tracker.iphone
        to: 'home'
      - platform: state
        entity_id: device_tracker.meghans_iphone
        to: 'home'
      - platform: event
        event_type: abode_automation
        event_data:
          device_name: 'Any phone enters -> Standby mode'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id: light.front_door
      - delay: 00:10
      - service: light.turn_off
        entity_id: light.front_door
# Turns on Living Room lights if first person gets home after sunset and before 11pm
  - alias: 'Any Entry After Sunset Before 10 -> Living Room On'
    trigger:
      - platform: state
        entity_id: device_tracker.iphone
        to: 'home'
      - platform: state
        entity_id: device_tracker.meghans_iphone
        to: 'home'
      - platform: event
        event_type: abode_automation
        event_data:
          device_name: 'Any phone enters -> Standby mode'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        after: '16:00:00'
        before: '22:00:00'
    action:
      service: light.turn_on
      entity_id: light.living_room
# Turns off devices and media autos if Abode goes to Away Mode
  - alias: 'Abode to Away -> Everything Off'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.abode
        to: 'armed_away'
    action:
      - service: script.turn_on
        entity_id: script.everything_off
      - service: homeassistant.turn_off
        entity_id: group.media_autos
# Turns off devices and media autos if 2AM and no one home (in case of power outage)
  - alias: '2 AM Away -> Everything Off'
    trigger:
      - platform: time
        at: '02:00:00'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
    action:
      service: script.turn_on
      entity_id: script.everything_off
# Switch Spotify
  - alias: 'Bedroom Echo -> Bedroom Stereo'
    trigger:
      - platform: state
        entity_id: media_player.spotify
        to: 'playing'
      - platform: state
        entity_id: sensor.spotify_source
        to: 'Bedroom Echo Dot'
    condition:
      - condition: state
        entity_id: sensor.spotify_source
        state: 'Bedroom Echo Dot'
    action:
      - service: script.turn_on
        entity_id: script.spotify_bedroom
  - alias: 'Living Room Echo -> Living Room Stereo'
    trigger:
      - platform: state
        entity_id: media_player.spotify
        to: 'playing'
      - platform: state
        entity_id: sensor.spotify_source
        to: 'Living Room Echo Dot'
    condition:
      - condition: state
        entity_id: sensor.spotify_source
        state: 'Living Room Echo Dot'
    action:
      - service: script.turn_on
        entity_id: script.spotify_living_room
  - alias: 'Kitchen Echo -> Kitchen Stereo'
    trigger:
      - platform: state
        entity_id: media_player.spotify
        to: 'playing'
      - platform: state
        entity_id: sensor.spotify_source
        to: 'Kitchen Echo Dot'
    condition:
      - condition: state
        entity_id: sensor.spotify_source
        state: 'Kitchen Echo Dot'
    action:
      - service: script.turn_on
        entity_id: script.spotify_kitchen
