- id: porch_light_off_20mins
  alias: Porch Light Off After 20 Mins
  trigger:
  - platform: state
    entity_id: light.front_door_light
    to: 'on'
    for: 00:20:00
  action:
  - service: light.turn_off
    data:
      entity_id: light.front_door_light
- id: remove_new_devices_notification
  alias: Remove new devices notification
  trigger:
  - platform: state
    entity_id: persistent_notification.config_entry_discovery
    to: notifying
  - platform: homeassistant
    event: start
  action:
  - service: persistent_notification.dismiss
    data:
      notification_id: config_entry_discovery
# - id: start_homekit2
#   alias: HA Starts, Wait 3 Mins + Start HomeKit
#   trigger:
#   - platform: homeassistant
#     event: start
#   action:
#   - delay: 00:03
#   - service: homekit.start
- id: time_for_bed_hue
  alias: Hold Hue On Button, Time For Bed
  trigger:
  - platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 1_hold
  action:
    service: script.turn_on
    data:
      entity_id: script.time_for_bed
- id: goodnight_hue
  alias: Hold Hue Off Button, Goodnight
  trigger:
  - platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 4_hold
  action:
    service: script.turn_on
    data:
      entity_id: script.goodnight
- id: standby_5am
  alias: 5 AM Present, Standby
  trigger:
  - platform: time
    at: 05:00:00
  condition:
  - condition: state
    entity_id: group.all_present
    state: 'on'
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.abode_alarm
- id: home_11pm
  alias: 11 PM Present, Home
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: group.all_present
    state: 'on'
  action:
  - service: alarm_control_panel.alarm_arm_home
    data:
      entity_id: alarm_control_panel.abode_alarm
  - service: lock.lock
    data:
      entity_id: lock.home_door_lock
- id: everything_off_2am
  alias: 2 AM Not Present, Everything Off
  trigger:
  - platform: time
    at: 02:00:00
  condition:
  - condition: state
    entity_id: group.all_present
    state: 'off'
  action:
  - service: script.turn_on
    data:
      entity_id: script.everything_off
- id: sleeping_off_6am
  alias: 6 AM, Sleeping Off
  trigger:
  - platform: time
    at: 06:00:00
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sleeping
- id: standby_arrival
  alias: Anyone Arrives, Standby
  trigger:
  - entity_id: binary_sensor.m_present
    platform: state
    to: 'on'
  - entity_id: binary_sensor.k_present
    platform: state
    to: 'on'
  - entity_id: input_boolean.x_present
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  action:
  - data:
      entity_id: alarm_control_panel.abode_alarm
    service: alarm_control_panel.alarm_disarm
- id: porch_light_on_arrival_night
  alias: Anyone Arrives At Night, Porch Light
  trigger:
  - entity_id: binary_sensor.m_present
    platform: state
    to: 'on'
  - entity_id: binary_sensor.k_present
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - before: '23:59'
    condition: time
  action:
  - data:
      entity_id: light.front_door_light
    service: light.turn_on
- id: living_room_lights_on_first_arrival
  alias: First Person Arrives At Night, Living Room Lights
  trigger:
  - entity_id: group.all_present
    platform: state
    to: 'on'
  - entity_id: group.core_present
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - before: '22:00:00'
    condition: time
  action:
  - data:
      entity_id: light.living_room_lights
    service: light.turn_on
- id: goodbye_last_exit
  alias: Last Person Leaves, Goodbye
  trigger:
  - platform: state
    entity_id: group.all_present
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  action:
  - service: script.turn_on
    data:
      entity_id: script.goodbye
- id: goodbye_away
  alias: Abode_alarm to Away, Goodbye
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
    to: armed_away
  action:
  - service: script.turn_on
    data:
      entity_id: script.goodbye
- id: mute_counter_1
  alias: Soundbar down 0 -> 1
  trigger:
  - platform: state
    entity_id: sensor.guest_room_volume
  condition:
  - condition: state
    entity_id: counter.mute_counter
    state: '0'
  - condition: template
    value_template: '{{ trigger.to_state.state < trigger.from_state.state }}'
  action:
  - service: counter.increment
    data:
      entity_id: counter.mute_counter
- id: mute_counter_2
  alias: Soundbar up 1 -> 2
  trigger:
  - platform: state
    entity_id: sensor.guest_room_volume
  condition:
  - condition: state
    entity_id: counter.mute_counter
    state: '1'
  - condition: template
    value_template: '{{ trigger.to_state.state > trigger.from_state.state }}'
  action:
  - service: counter.increment
    data:
      entity_id: counter.mute_counter
- id: mute_complete
  alias: Soundbar down 2 -> mute
  trigger:
  - platform: state
    entity_id: sensor.guest_room_volume
  condition:
  - condition: state
    entity_id: counter.mute_counter
    state: '2'
  - condition: template
    value_template: '{{ trigger.to_state.state < trigger.from_state.state }}'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.guest_room_stereo_main
      is_volume_muted: true
- id: mute_counter_0_idle
  alias: Mute Counter Idle -> 0
  trigger:
  - platform: state
    entity_id: counter.mute_counter
    to: '1'
    for: 00:00:03
  - platform: state
    entity_id: counter.mute_counter
    to: '2'
    for: 00:00:03
  action:
  - service: counter.reset
    data:
      entity_id: counter.mute_counter
- id: auto_lock
  alias: Lock After 20 Minutes
  description: ''
  trigger:
  - entity_id: binary_sensor.unlocked_closed
    for: 00:20:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: lock.home_door_lock
    service: lock.lock
- id: sonos_volume_up_group
  alias: Volume Up, Sonos Group
  description: ''
  trigger:
  - entity_id: sensor.bedroom_volume
    platform: state
  - entity_id: sensor.kitchen_volume
    platform: state
  - entity_id: sensor.living_room_volume
    platform: state
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state > trigger.from_state.state }}'
  - condition: template
    value_template: '{{ not is_state(''media_player.''+trigger.entity_id.replace(''sensor.'',
      '''').replace(''_volume'',''''), ''playing'') }}

      '
  action:
  - data_template:
      target_player: media_player.{{ trigger.entity_id.replace('sensor.', '').replace('_volume',
        '') }}
    service: script.sonos_group_if_playing
- id: sonos_volume_down_move
  alias: Volume Down, Sonos Move
  description: ''
  trigger:
  - entity_id: sensor.bedroom_volume
    platform: state
  - entity_id: sensor.kitchen_volume
    platform: state
  - entity_id: sensor.living_room_volume
    platform: state
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state < trigger.from_state.state }}'
  - condition: template
    value_template: '{{ not is_state(''media_player.''+trigger.entity_id.replace(''sensor.'',
      '''').replace(''_volume'',''''), ''playing'') }}

      '
  action:
  - service: script.sonos_move_if_playing
    data_template:
      new_player: '{{ trigger.entity_id.replace(''sensor.'', ''media_player.'').replace(''_volume'',
        '''') }}'
      old_player: '{{ ''media_player.'' + states(''input_select.music_controller'')
        }}'
- id: sonos_volume_ungroup
  alias: Volume Change, Sonos Ungroup
  description: ''
  trigger:
  - entity_id: sensor.bedroom_volume
    platform: state
  - entity_id: sensor.kitchen_volume
    platform: state
  - entity_id: sensor.living_room_volume
    platform: state
  condition:
  - condition: template
    value_template: '{{ not is_state(''media_player.''+trigger.entity_id.replace(''sensor.'',
      '''').replace(''_volume'',''''), ''playing'') }}

      '
  - condition: template
    value_template: '{{ not is_state(''media_player.'' + states(''input_select.music_controller''),
      ''playing'') }}

      '
  action:
  - service: sonos.unjoin
    data_template:
      entity_id: '{{ ''media_player.''+trigger.entity_id.replace(''sensor.'', '''').replace(''_volume'','''')
        }}'
- id: sonos_play_change_controller
  alias: Sonos Play, Change Music Controller
  description: ''
  trigger:
  - entity_id: media_player.bedroom
    platform: state
    to: playing
  - entity_id: media_player.kitchen
    platform: state
    to: playing
  - entity_id: media_player.living_room
    platform: state
    to: playing
  condition: []
  action:
  - data_template:
      target_player: '{{ trigger.entity_id }}'
    service: script.sonos_set_controller
- id: '1585541724720'
  alias: Reset pressed_pause
  description: ''
  trigger:
  - entity_id: input_boolean.pressed_pause_bedroom
    for: 00:00:03
    platform: state
    to: 'on'
  - entity_id: input_boolean.pressed_pause_kitchen
    for: 00:00:03
    platform: state
    to: 'on'
  - entity_id: input_boolean.pressed_pause_living_room
    for: 00:00:03
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.entity_id }}'
    service: input_boolean.turn_off
- id: '1585541805967'
  alias: Press Pause, Turn On pressed_pause
  description: ''
  trigger:
  - entity_id: media_player.bedroom
    from: playing
    platform: state
    to: paused
  - entity_id: media_player.kitchen
    from: playing
    platform: state
    to: paused
  - entity_id: media_player.living_room
    from: playing
    platform: state
    to: paused
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.entity_id.replace(''media_player.'', ''input_boolean.pressed_pause_'')
        }}'
    service: input_boolean.turn_on
- id: '1585541929094'
  alias: Press Play With pressed_pause On, Next Track
  description: ''
  trigger:
  - entity_id: media_player.bedroom
    from: paused
    platform: state
    to: playing
  - entity_id: media_player.kitchen
    from: paused
    platform: state
    to: playing
  - entity_id: media_player.living_room
    from: paused
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ is_state(trigger.entity_id.replace(''media_player.'', ''input_boolean.pressed_pause_''),
      ''on'') }}'
  action:
  - data_template:
      entity_id: '{{ trigger.entity_id }}'
    service: media_player.media_next_track
- id: spotify_guest_room_echo
  alias: Spotify from Guest Room Echo to Stereo
  trigger:
  - entity_id: sensor.spotify_source
    platform: state
    to: Guest Room Echo Dot
  action:
    service: script.spotify_guest_room
- id: apple_watch_group
  alias: AW Group
  trigger:
  - event_data:
      actionName: bedroom
    event_type: ios.action_fired
    platform: event
  - event_data:
      actionName: kitchen
    event_type: ios.action_fired
    platform: event
  - event_data:
      actionName: living_room
    event_type: ios.action_fired
    platform: event
  action:
  - service: script.sonos_group
    data_template:
      target_player: '{{ ''media_player.'' + trigger.event.data.actionName }}'
- id: notify_garage
  alias: Notify When Garage Is Open
  description: ''
  trigger:
  - entity_id: cover.garage_door
    for: 00:20:00
    platform: state
    to: open
  - entity_id: cover.garage_door
    for: 00:40:00
    platform: state
    to: open
  - entity_id: cover.garage_door
    for: 01:00:00
    platform: state
    to: open
  condition: []
  action:
  - data_template:
      data:
        push:
          badge: 0
          category: garage
      message: >
        Hey silly, the garage has been open for {{ (trigger.for|string)[2:4].replace('00','60') }} minutes!
      title: Garage Open
    service: notify.mobile_app_eye_phone
  - data_template:
      data:
        push:
          badge: 0
          category: garage
      message: >
        Hey silly, the garage has been open for {{ (trigger.for|string)[2:4].replace('00','60') }} minutes!
      title: Garage Open
    service: notify.mobile_app_meghans_iphone
- id: ios_garage_triggered
  alias: iOS - Garage Triggered Action
  trigger:
  - event_data:
      actionName: GARAGE_CLOSE
    event_type: ios.notification_action_fired
    platform: event
  action:
  - entity_id: cover.garage_door
    service: cover.close_cover

- id: notify_door
  alias: Notify When A Door Is Open
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door
    for: 00:20:00
    platform: state
    to: 'on'
  - entity_id: binary_sensor.front_door
    for: 00:40:00
    platform: state
    to: 'on'
  - entity_id: binary_sensor.front_door
    for: 01:00:00
    platform: state
    to: 'on'
  - entity_id: binary_sensor.side_door
    for: 00:20:00
    platform: state
    to: 'on'
  - entity_id: binary_sensor.side_door
    for: 00:40:00
    platform: state
    to: 'on'
  - entity_id: binary_sensor.side_door
    for: 01:00:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      message: >
        Hey silly, the {{ state_attr(trigger.entity_id, 'friendly_name')|lower }} has been open for {{ (trigger.for|string)[2:4].replace('00','60') }} minutes!
      title: >
        {{ state_attr(trigger.entity_id, 'friendly_name') }} Open
    service: notify.mobile_app_eye_phone
  - data_template:
      message: >
        Hey silly, the {{ state_attr(trigger.entity_id, 'friendly_name')|lower }} has been open for {{ (trigger.for|string)[2:4].replace('00','60') }} minutes!
      title: >
        {{ state_attr(trigger.entity_id, 'friendly_name') }} Open
    service: notify.mobile_app_meghans_iphone

- id: soundbar_off_light_on
  alias: Soundbar Off, Light On
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.guest_room_stereo_main
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.guests_visiting
    state: 'off'
  - condition: time
    after: '20:00'
  action:
  - service: light.turn_on
    entity_id: light.living_room_lights
  - service: light.turn_on
    entity_id: light.bedroom_lights
  - service: light.turn_on
    data:
      entity_id: light.guest_room
      brightness_pct: 100
  - service: light.turn_off
    data:
      entity_id: light.guest_room
      transition: 300
