- platform: template
  sensors:
    k_present:
      friendly_name: "K Home"
      value_template: >-
        {{ is_state('input_boolean.k_present','on') or 
           is_state('device_tracker.k_iphone','home') }}
    m_present:
      friendly_name: "M Home"
      value_template: >-
        {{ is_state('input_boolean.m_present','on') or 
           is_state('device_tracker.m_iphone','home') }}
    unlocked_closed:
      friendly_name: "Front Door Unlocked and Closed"
      value_template: >-
        {{ is_state('lock.home_door_lock','unlocked') and 
           is_state('binary_sensor.front_door','off') }}
    closed_light:
      friendly_name: "Front Door Unlocked and Closed and Light On"
      value_template: >-
        {{ is_state('binary_sensor.front_door','off') and
           is_state('light.front_door','on') }}
    alexa_ha_nightlight:
      friendly_name: "Alexa HA - Nightlight"
      device_class: window
      value_template: "{{ is_state('input_boolean.alexa_ha_nightlight', 'on') }}"
    alexa_ha_plug:
      friendly_name: "Alexa HA - Plug"
      device_class: window
      value_template: "{{ is_state('input_boolean.alexa_ha_plug', 'on') }}"