homeassistant:
  # Name of the location where Home Assistant is running
  # name: Home
  # Location required to calculate the time the sun rises and sets
  # latitude: !secret lat
  # longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: 0
  # metric for Metric, imperial for Imperial
  # unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: America/Los_Angeles
  # Trusted networks
  # auth_providers:
  #   - type: homeassistant
  #   - type: trusted_networks
  #     trusted_networks:
  #       - !secret iphone_ip  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables system health
system_health:

# Enables Hass IO UI
hassio:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - google_cast
    - igd
    - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#iOS
ios:

# Virtual Echo
#rest_command:
#  ask_alexa:
#    url: !secret virtual_echo_url

# Sensors
sensor:
  # Hue custom component
  - platform: huesensor
  # Weather prediction
  - platform: yr
  # Spotify source
  - platform: template
    sensors:
      spotify_source:
        value_template: '{{ states.media_player.spotify.attributes["source"] }}'
        friendly_name: 'Spotify Source'
      bedroom_stereo_main_source:
        value_template: '{{ states.media_player.bedroom_stereo_main.attributes["source"] }}'
        friendly_name: 'Bedroom Stereo Source'
      kitchen_stereo_main_source:
        value_template: '{{ states.media_player.kitchen_stereo_main.attributes["source"] }}'
        friendly_name: 'Kitchen Stereo Source'

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Device Tracker
device_tracker:
  - platform: netgear
    password: !secret netgear_password
    new_device_defaults:
      track_new_devices: false
    interval_seconds: 30
    consider_home: 0:20

emulated_hue:
  host_ip: !secret hassio_ip
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - script
    - switch
  off_maps_to_on_domains:
    - script
    - scene
  entities:
    script.good_morning:
      hidden: true
    switch.outdoor_switch_00420738:
      name: "Backyard Lights"
      hidden: false
    switch.good_morning:
      hidden: true
    switch.everything_off:
      hidden: true
    switch.night_time:
      hidden: true
    switch.goodnight:
      hidden: true
    switch.time_for_bed:
      hidden: true
    switch.tv_time:
      hidden: true
    switch.goodbye:
      hidden: true

# Switches for HomeKit
switch:
  - platform: template
    switches:
      media_autos:
        friendly_name: 'Media Automations'
        value_template: "{{ is_state('group.media_autos', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.media_autos
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.media_autos
      all_stereos:
        friendly_name: 'All Stereos'
        value_template: >-
          {{  not is_state('media_player.living_room_stereo_main', 'off') or
              not is_state('media_player.bedroom_stereo_main', 'off') or
              not is_state('media_player.kitchen_stereo_main', 'off') or
              not is_state('media_player.guest_room_stereo_main', 'off') or
              not is_state('media_player.basement_stereo_main', 'off')
          }}
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.all_stereos
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.all_stereos
      good_morning:
        friendly_name: 'Good Morning'
        value_template: >-
          {{  is_state('alarm_control_panel.abode', 'disarmed') and
              is_state('group.media_autos', 'on')
          }}
        turn_on:
          service: script.turn_on
          entity_id: script.good_morning
        turn_off:
      everything_off:
        friendly_name: 'Everything Off'
        value_template: >-
          {{  is_state('media_player.living_room_stereo_main', 'off') and
              is_state('media_player.bedroom_stereo_main', 'off') and
              is_state('media_player.kitchen_stereo_main', 'off') and
              is_state('media_player.guest_room_stereo_main', 'off') and
              is_state('media_player.basement_stereo_main', 'off') and
              is_state('group.all_lights', 'off') and
              is_state('cover.garage_door', 'closed')
          }}
        turn_on:
          service: script.turn_on
          entity_id: script.everything_off
        turn_off:
      night_time:
        friendly_name: 'Night Time'
        value_template: >-
          {{  is_state('group.media_autos', 'off') and
              is_state('alarm_control_panel.abode', 'armed_home')
          }}
        turn_on:
          service: script.turn_on
          entity_id: script.night_time
        turn_off:
      goodnight:
        friendly_name: 'Goodnight'
        value_template: >-
          {{  is_state('switch.everything_off', 'on') and
              is_state('switch.night_time', 'on')
          }}
        turn_on:
          service: script.turn_on
          entity_id: script.goodnight
        turn_off:
      time_for_bed:
        friendly_name: 'Time For Bed'
        value_template: >-
          {{  is_state('media_player.living_room_stereo_main', 'off') and
              is_state('media_player.kitchen_stereo_main', 'off') and
              is_state('media_player.guest_room_stereo_main', 'off') and
              is_state('media_player.basement_stereo_main', 'off') and
              is_state('group.base', 'off') and
              is_state('switch.night_time', 'on') and
              is_state('group.guest_room', 'off') and
              is_state('light.bedroom', 'on')
          }}
        turn_on:
          service: script.turn_on
          entity_id: script.time_for_bed
        turn_off:
      tv_time:
        friendly_name: 'TV Time'
        value_template: >-
          {{  is_state('media_player.living_room_stereo_main', 'off') and
              is_state('media_player.bedroom_stereo_main', 'off') and
              is_state('media_player.kitchen_stereo_main', 'off') and
              is_state('media_player.basement_stereo_main', 'off') and
              is_state('group.base', 'off') and
              is_state('group.bedroom', 'off')
          }}
        turn_on:
          service: script.turn_on
          entity_id: script.tv_time
        turn_off:
      goodbye:
        friendly_name: 'Goodbye'
        value_template: >-
          {{  is_state('alarm_control_panel.abode', 'armed_away') and
              is_state('switch.everything_off', 'on') and
              is_state('group.media_autos', 'off')
          }}
        turn_on:
          service: script.turn_on
          entity_id: script.goodbye
        turn_off:

# HomeKit
homekit:
  auto_start: False
  filter:
    include_domains:
      - cover
      - media_player
      - alarm_control_panel
      - light
      - switch
      - script
    include_entities:
      - binary_sensor.front_door
      - binary_sensor.side_door
    exclude_entities:
      - light.backyard
      - light.guest_room
      - light.porch_lamp
      - script.close_garage
      - script.night_time
      - script.good_morning
      - script.everything_off
      - script.night_time
      - script.goodnight
      - script.time_for_bed
      - script.tv_time
      - script.goodbye
      - media_player.den_tv
      - switch.night_time
  entity_config:
    light.living_room:
      name: "Living Room Lights"
    light.bedroom:
      name: "Bedroom Lights"
    light.basement:
      name: "Basement Lights"
    light.front_door:
      name: "Front Door Light"
    switch.outdoor_switch_00420738:
      name: "Backyard Lights"
    media_player.living_room_stereo_main:
      name: "Living Room Stereo"
      feature_list:
        - feature: on_off
    media_player.kitchen_stereo_main:
      name: "Kitchen Stereo"
      feature_list:
        - feature: on_off
    media_player.bedroom_stereo_main:
      name: "Bedroom Stereo"
      feature_list:
        - feature: on_off
    media_player.basement_stereo_main:
      name: "Basement Stereo"
      feature_list:
        - feature: on_off
    media_player.guest_room_stereo_main:
      name: "Guest Room Stereo"
      feature_list:
        - feature: on_off
    media_player.vizio_smartcast:
      name: "TV"
      feature_list:
        - feature: on_off

# Hue
hue:
  bridges:
    - host: !secret hue_ip

# Garage Door
cover:
  - platform: myq
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain

# Abode Alarm System
abode:
  username: !secret abode_username
  password: !secret abode_password
  name: Abode

# Yamaha and Spotify
media_player:
  - platform: yamaha_musiccast
    host: !secret lr_stereo_ip
    port: 5005
  - platform: yamaha_musiccast
    host: !secret ki_stereo_ip
    port: 5006
  - platform: yamaha_musiccast
    host: !secret br_stereo_ip
    port: 5007
  - platform: yamaha_musiccast
    host: !secret ba_stereo_ip
    port: 5008
  - platform: yamaha_musiccast
    host: !secret gr_stereo_ip
    port: 5009
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    aliases:
      !secret lr_stereo_alias: 'Living Room Stereo'
      !secret br_stereo_alias: 'Bedroom Stereo'
      !secret gr_stereo_alias: 'Guest Room Stereo'
      !secret ki_stereo_alias: 'Kitchen Stereo'
      !secret ba_stereo_alias: 'Basement Stereo'
      !secret lr_dot_alias: 'Living Room Echo Dot'
      !secret ki_dot_alias: 'Kitchen Echo Dot'
      !secret br_dot_alias: 'Bedroom Echo Dot'
  - platform: vizio
    host: !secret vizio_ip
    access_token: !secret vizio_auth_token

# Log to get Spotify aliases
logger:
  default: warning
  logs:
    homeassistant.components.media_player.spotify: info

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
