homeassistant:
  customize: !include customize.yaml

# Add default configuration
default_config:

# Enables Hass IO UI
hassio:

# Discover some devices automatically
discovery:
  ignore:
    - google_cast
    - igd
    - homekit
    - yamaha

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - input_boolean.k_present
      - input_boolean.m_present
      - automation.remove_new_devices_notification

# Alexa Smart Home Skill
api:

alexa:
  smart_home:
    filter:
      include_domains:
        - switch
        - script
      exclude_entities:
        - script.spotify_switch
        - script.standby

# Input booleans
input_boolean:
  guests_visiting:
    name: Guest Room Guests
    icon: mdi:account-multiple
  sleeping:
    name: Sleeping boolean
    icon: mdi:sleep
  k_present:
    name: K Home, Homekit
    icon: mdi:account
  m_present:
    name: M Home, Homekit
    icon: mdi:account
  x_present:
    name: Any Home, Homekit
    icon: mdi:account

# Counter for muting Guest Room Stereo
counter:
  mute_counter:
    initial: 0
    step: 1
    minimum: 0
    maximum: 2

# Binary sensors
binary_sensor:
  # K present
  - platform: template
    sensors:
      k_present:
        friendly_name: "K Home"
        value_template: >-
          {{ is_state('input_boolean.k_present','on') or 
             is_state('device_tracker.k_iphone','home') }}
      m_present:
        friendly_name: "M Home"
        value_template: >-
          {{ is_state('input_boolean.m_present','on') or 
             is_state('device_tracker.m_iphone','home') }}
      unlocked_closed:
        friendly_name: "Front Door Unlocked and Closed"
        value_template: >-
          {{ is_state('lock.home_door_lock','unlocked') and 
             is_state('binary_sensor.front_door','off') }}

# Sensors
sensor:
  # Hue custom component (installed in config/custom_components/huesensor/)
  - platform: huesensor
  # Weather prediction
  # - platform: yr
  # Spotify source
  - platform: template
    sensors:
      spotify_source:
        value_template: '{{ state_attr("media_player.spotify", "source") }}'
        friendly_name: 'Spotify Source'
      living_room_volume:
        value_template: '{{ state_attr("media_player.living_room_stereo_main", "volume_level") | float }}'
        friendly_name: 'Living Room Volume'
      bedroom_volume:
        value_template: '{{ state_attr("media_player.bedroom_stereo_main", "volume_level") | float }}'
        friendly_name: 'Bedroom Volume'
      kitchen_volume:
        value_template: '{{ state_attr("media_player.kitchen_stereo_main", "volume_level") | float }}'
        friendly_name: 'Kitchen Volume'
      basement_volume:
        value_template: '{{ state_attr("media_player.basement_stereo_main", "volume_level") | float }}'
        friendly_name: 'Basement Volume'
      guest_room_volume:
        value_template: '{{ state_attr("media_player.guest_room_stereo_main", "volume_level") | float }}'
        friendly_name: 'Guest Room Volume'

# Device Tracker
device_tracker:
  - platform: netgear
    password: !secret netgear_password
    devices:
      - !secret m_mac
      - !secret k_mac
    new_device_defaults:
      track_new_devices: false
    interval_seconds: 30
    consider_home: 3:00

# HomeKit
homekit:
  auto_start: False
  filter:
    include_domains:
      - cover
      - media_player
      - alarm_control_panel
      - light
      - switch
      - script
      - input_boolean
      - input_number
      - lock
    include_entities:
      - binary_sensor.front_door
      - binary_sensor.side_door
    exclude_entities:
      - light.backyard
      - light.guest_room
      - light.porch_lamp
    #   - media_player.vizio_smartcast
      - script.close_garage
      - script.spotify_switch
      - input_boolean.k_entered
      - input_boolean.m_entered
      - script.lock_if_closed
      - script.spotify_living_room_check_if_on
  entity_config:
    input_boolean.k_present:
      name: "K Home"
    input_boolean.m_present:
      name: "M Home"
    media_player.living_room_stereo_main:
      name: "Living Room Stereo"
      feature_list:
        - feature: on_off
    media_player.kitchen_stereo_main:
      name: "Kitchen Stereo"
      feature_list:
        - feature: on_off
    media_player.bedroom_stereo_main:
      name: "Bedroom Stereo"
      feature_list:
        - feature: on_off
    media_player.basement_stereo_main:
      name: "Basement Stereo"
      feature_list:
        - feature: on_off
    media_player.guest_room_stereo_main:
      name: "Guest Room Stereo"
      feature_list:
        - feature: on_off
    light.bedroom:
      name: "Bedroom Lights"
    light.living_room:
      name: "Living Room Lights"
    light.basement:
      name: "Basement Lights"
    light.front_door:
      name: "Front Door Light"

# Hue
hue:
  bridges:
    - host: !secret hue_ip

# Garage Door
cover:
  - platform: myq
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain

# Yamaha
media_player:
  - platform: yamaha_musiccast
    host: !secret lr_stereo_ip
    port: 5005
  - platform: yamaha_musiccast
    host: !secret ki_stereo_ip
    port: 5006
  - platform: yamaha_musiccast
    host: !secret br_stereo_ip
    port: 5007
  - platform: yamaha_musiccast
    host: !secret ba_stereo_ip
    port: 5008
  - platform: yamaha_musiccast
    host: !secret gr_stereo_ip
    port: 5009

# Spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
    # aliases:
    #   !secret lr_stereo_alias: 'Living Room Stereo'
    #   !secret br_stereo_alias: 'Bedroom Stereo'
    #   !secret gr_stereo_alias: 'Guest Room Stereo'
    #   !secret ki_stereo_alias: 'Kitchen Stereo'
    #   !secret ba_stereo_alias: 'Basement Stereo'
    #   !secret lr_dot_alias: 'Living Room Echo Dot'
    #   !secret ki_dot_alias: 'Kitchen Echo Dot'
    #   !secret br_dot_alias: 'Bedroom Echo Dot'

# Log to get Spotify aliases
logger:
  default: warning
  logs:
    homeassistant.components.media_player.spotify: info

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
