homeassistant:
  customize: !include customize.yaml

# Add default configuration
default_config:

# Enables Hass IO UI
hassio:

# Discover some devices automatically
discovery:
  ignore:
    - google_cast
    - homekit
    - yamaha
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - input_boolean.k_present
      - input_boolean.m_present
      - automation.remove_new_devices_notification

# Upstairs lights
light:
  - platform: template
    lights:
      upstairs_lights:
        friendly_name: "Upstairs Lights"
        value_template: "{{ is_state('group.upstairs_lights', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.upstairs_lights
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.upstairs_lights

# iOS garage alert action
ios:
  push:
    categories:
      - name: garage_trigger
        identifier: 'garage'
        actions:
          - identifier: 'GARAGE_CLOSE'
            title: 'Close Garage'
            authenticationRequired: no
            destructive: no

# Music Controller
input_select:
  music_controller:
    name: Music Controller
    options:
      - bedroom
      - kitchen
      - living_room
      - office

# Netgear
device_tracker:
  - platform: netgear
    password: !secret netgear_password
    host: !secret netgear_host
    devices:
      - !secret m_mac
      - !secret k_mac
    new_device_defaults:
      track_new_devices: false
    interval_seconds: 30
    consider_home: 3:00

# Yamaha
media_player:
  - platform: yamaha_musiccast
    host: !secret gr_stereo_ip
    port: !secret gr_stereo_port

# Spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Sonos
sonos:
  media_player:
    advertise_addr: !secret sonos_advertise_addr

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

input_boolean: !include input_boolean.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
alexa: !include alexa.yaml
homekit: !include homekit.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
