homeassistant:
  customize: !include customize.yaml

# Add default configuration
default_config:

# Enables Hass IO UI
hassio:

# View all events in a logbook
# logbook:
#   exclude:
#     entities:
#       - input_boolean.k_present
#       - input_boolean.m_present
#       - automation.remove_new_devices_notification

logger:
  default: warning

recorder:
  commit_interval: 30
#   include:
#     domains:
#       - light

# Upstairs lights
light:
  - platform: template
    lights:
      upstairs:
        friendly_name: "Upstairs"
        value_template: "{{ is_state('group.upstairs_lights', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.upstairs_lights
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.upstairs_lights
        icon_template:
          mdi:lightbulb-group
switch:
  - platform: template
    switches:
      apple_tv:
        friendly_name: "Apple TV Controller"
        value_template: "{{ not (is_state('media_player.guest_room', 'standby') or is_state('media_player.guest_room', 'paused')) }}"
        turn_on:
          service: script.apple_tv_on
        turn_off:
          service: script.apple_tv_off
        icon_template:
          mdi:apple
      tempo:
        friendly_name: "Tempo"
        value_template: "{{ is_state('media_player.tv', 'ok') and 'Tempo' == state_attr('media_player.tv', 'source') }}"
        turn_on:
          service: script.tempo_on
        turn_off:
          service: script.apple_tv_off
        icon_template:
          mdi:dumbbell

# Music Controller
input_select:
  music_controller:
    name: Music Controller
    options:
      - bedroom
      - kitchen
      - living_room
      - office

# Sonos
sonos:
  media_player:
    advertise_addr: !secret sonos_advertise_addr

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

input_boolean: !include input_boolean.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
alexa: !include alexa.yaml
homekit: !include homekit.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
