homeassistant:
  customize: !include customize.yaml
  # Name of the location where Home Assistant is running
  # name: Home
  # Location required to calculate the time the sun rises and sets
  # latitude: !secret lat
  # longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: 0
  # metric for Metric, imperial for Imperial
  # unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: America/Los_Angeles
  # Trusted networks
  # auth_providers:
  #   - type: homeassistant
  #   - type: trusted_networks
  #     trusted_networks:
  #       - !secret iphone_ip  # Customization file

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables system health
system_health:

# Enables Hass IO UI
hassio:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - google_cast
    - igd
    - homekit
    - yamaha

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - input_boolean.k_present
      - input_boolean.m_present
      - automation.remove_new_devices_notification

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Alexa Smart Home Skill
api:

alexa:
  smart_home:
    filter:
      include_domains:
        - switch
        - script
      exclude_entities:
        - script.spotify_switch
        - script.standby

# emulated_hue:
#   host_ip: !secret hassio_ip
#   listen_port: 80
#   expose_by_default: true
#   exposed_domains:
#     - script
#     - switch
#   off_maps_to_on_domains:
#     - script
#   entities:
#     script.spotify_switch:
#       hidden: true
#     script.standby:
#       hidden: true

# Virtual Echo
#rest_command:
#  ask_alexa:
#    url: !secret virtual_echo_url

# Input booleans
input_boolean:
  guests_visiting:
    name: Guest Room Guests
    icon: mdi:account-multiple
  sleeping:
    name: Sleeping boolean
    icon: mdi:sleep
  k_present:
    name: K Home, Homekit
    icon: mdi:account
  m_present:
    name: M Home, Homekit
    icon: mdi:account
#   k_entered:
#     name: K Entered Wi-Fi
#     icon: mdi:wifi-star
#   m_entered:
#     name: M Entered Wi-Fi
#     icon: mdi:wifi-star

# Counter for muting Guest Room Stereo
counter:
  mute_counter:
    initial: 0
    step: 1
    minimum: 0
    maximum: 2

# Dark Sky Weather API
# weather:
#   - platform: darksky
#     api_key: !secret dark_sky_api_key

# Binary sensors
binary_sensor:
  # K present
  - platform: template
    sensors:
      k_present:
        friendly_name: "K Home"
        value_template: >-
          {{ is_state('input_boolean.k_present','on') or 
             is_state('device_tracker.k_iphone','home') or 
             is_state('device_tracker.k_watch','home') }}
      m_present:
        friendly_name: "M Home"
        value_template: >-
          {{ is_state('input_boolean.m_present','on') or 
             is_state('device_tracker.m_iphone','home') }}

# Sensors
sensor:
  # Hue custom component (installed in config/custom_components/huesensor/)
  - platform: huesensor
  # Weather prediction
  # - platform: yr
  # Spotify source
  - platform: template
    sensors:
      spotify_source:
        value_template: '{{ state_attr("media_player.spotify", "source") }}'
        friendly_name: 'Spotify Source'
      living_room_volume:
        value_template: '{{ state_attr("media_player.living_room_stereo_main", "volume_level") | float }}'
        friendly_name: 'Living Room Volume'
      bedroom_volume:
        value_template: '{{ state_attr("media_player.bedroom_stereo_main", "volume_level") | float }}'
        friendly_name: 'Bedroom Volume'
      kitchen_volume:
        value_template: '{{ state_attr("media_player.kitchen_stereo_main", "volume_level") | float }}'
        friendly_name: 'Kitchen Volume'
      basement_volume:
        value_template: '{{ state_attr("media_player.basement_stereo_main", "volume_level") | float }}'
        friendly_name: 'Basement Volume'
      guest_room_volume:
        value_template: '{{ state_attr("media_player.guest_room_stereo_main", "volume_level") | float }}'
        friendly_name: 'Guest Room Volume'
    #   gold_lamp_available:
    #     friendly_name: "gold_lamp available"
    #     unit_of_measurement: '%'
    #     icon_template: mdi:battery-charging-100
    #     value_template: >-
    #       {% if is_state('light.gold_lamp','unavailable') %}
    #         0
    #       {% else %}
    #         100
    #       {% endif %}
    #   elephant_lamp_available:
    #     friendly_name: "elephant_lamp available"
    #     unit_of_measurement: '%'
    #     icon_template: mdi:battery-charging-100
    #     value_template: >-
    #       {% if is_state('light.elephant_lamp','unavailable') %}
    #         0
    #       {% else %}
    #         100
    #       {% endif %}
    #   basement_light_1_available:
    #     friendly_name: "basement_light_1 available"
    #     unit_of_measurement: '%'
    #     icon_template: mdi:battery-charging-100
    #     value_template: >-
    #       {% if is_state('light.basement_light_1','unavailable') %}
    #         0
    #       {% else %}
    #         100
    #       {% endif %}
    #   basement_light_2_available:
    #     friendly_name: "basement_light_2 available"
    #     unit_of_measurement: '%'
    #     icon_template: mdi:battery-charging-100
    #     value_template: >-
    #       {% if is_state('light.basement_light_2','unavailable') %}
    #         0
    #       {% else %}
    #         100
    #       {% endif %}
    #   front_door_available:
    #     friendly_name: "front_door available"
    #     unit_of_measurement: '%'
    #     icon_template: mdi:battery-charging-100
    #     value_template: >-
    #       {% if is_state('light.front_door','unavailable') %}
    #         0
    #       {% else %}
    #         100
    #       {% endif %}

# Text to speech
# tts:
#   - platform: google_translate
#     service_name: google_say

# Device Tracker
device_tracker:
  - platform: netgear
    password: !secret netgear_password
    devices:
      - !secret m_mac
      - !secret k_mac
      - !secret k_watch_mac
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
    interval_seconds: 30
    consider_home: 3:00

# Switch Templates for HomeKit
# switch:
#   - platform: template
    # switches:
    #   media_autos:
    #     friendly_name: 'Media Automations'
    #     value_template: "{{ is_state('group.media_autos', 'on') }}"
    #     turn_on:
    #       service: homeassistant.turn_on
    #       entity_id: group.media_autos
    #     turn_off:
    #       service: homeassistant.turn_off
    #       entity_id: group.media_autos
    #   all_stereos:
    #     friendly_name: 'All Stereos'
    #     value_template: >-
    #       {{  not is_state('media_player.living_room_stereo_main', 'off') or
    #           not is_state('media_player.bedroom_stereo_main', 'off') or
    #           not is_state('media_player.kitchen_stereo_main', 'off') or
    #           not is_state('media_player.guest_room_stereo_main', 'off') or
    #           not is_state('media_player.basement_stereo_main', 'off')
    #       }}
    #     turn_on:
    #       service: homeassistant.turn_on
    #       entity_id: group.all_stereos
    #     turn_off:
    #       service: homeassistant.turn_off
    #       entity_id: group.all_stereos

# HomeKit
homekit:
  auto_start: False
  filter:
    include_domains:
      - cover
      - media_player
      - alarm_control_panel
      - light
      - switch
      - script
      - input_boolean
      - input_number
      - lock
    include_entities:
      - binary_sensor.front_door
      - binary_sensor.side_door
    exclude_entities:
      - light.backyard
      - light.guest_room
      - light.porch_lamp
      - media_player.vizio_smartcast
      - script.close_garage
      - script.spotify_switch
      - input_boolean.k_entered
      - input_boolean.m_entered
      - script.lock_if_closed
  entity_config:
    input_boolean.k_present:
      name: "K Home"
    input_boolean.m_present:
      name: "M Home"
    media_player.living_room_stereo_main:
      name: "Living Room Stereo"
      feature_list:
        - feature: on_off
    media_player.kitchen_stereo_main:
      name: "Kitchen Stereo"
      feature_list:
        - feature: on_off
    media_player.bedroom_stereo_main:
      name: "Bedroom Stereo"
      feature_list:
        - feature: on_off
    media_player.basement_stereo_main:
      name: "Basement Stereo"
      feature_list:
        - feature: on_off
    media_player.guest_room_stereo_main:
      name: "Guest Room Stereo"
      feature_list:
        - feature: on_off
    light.bedroom:
      name: "Bedroom Lights"
    # light.gold_lamp:
    #   linked_battery_sensor: sensor.gold_lamp_available
    #   low_battery_threshold: 50
    # light.elephant_lamp:
    #   linked_battery_sensor: sensor.elephant_lamp_available
    #   low_battery_threshold: 50
    light.living_room:
      name: "Living Room Lights"
    #   linked_battery_sensor: sensor.elephant_lamp_available
    #   low_battery_threshold: 50
    # light.basement_light_1:
    #   linked_battery_sensor: sensor.basement_light_1_available
    #   low_battery_threshold: 50
    # light.basement_light_2:
    #   linked_battery_sensor: sensor.basement_light_2_available
    #   low_battery_threshold: 50
    light.basement:
      name: "Basement Lights"
    #   linked_battery_sensor: sensor.basement_light_1_available
    #   low_battery_threshold: 50
    light.front_door:
      name: "Front Door Light"
    #   linked_battery_sensor: sensor.front_door_available
    #   low_battery_threshold: 50

# Hue
hue:
  bridges:
    - host: !secret hue_ip

# Garage Door
cover:
  - platform: myq
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain

# Abode Alarm System
abode:
  username: !secret abode_username
  password: !secret abode_password

# Yamaha and Spotify
media_player:
  - platform: yamaha_musiccast
    host: !secret lr_stereo_ip
    port: 5005
  - platform: yamaha_musiccast
    host: !secret ki_stereo_ip
    port: 5006
  - platform: yamaha_musiccast
    host: !secret br_stereo_ip
    port: 5007
  - platform: yamaha_musiccast
    host: !secret ba_stereo_ip
    port: 5008
  - platform: yamaha_musiccast
    host: !secret gr_stereo_ip
    port: 5009
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    aliases:
      !secret lr_stereo_alias: 'Living Room Stereo'
      !secret br_stereo_alias: 'Bedroom Stereo'
      !secret gr_stereo_alias: 'Guest Room Stereo'
      !secret ki_stereo_alias: 'Kitchen Stereo'
      !secret ba_stereo_alias: 'Basement Stereo'
      !secret lr_dot_alias: 'Living Room Echo Dot'
      !secret ki_dot_alias: 'Kitchen Echo Dot'
      !secret br_dot_alias: 'Bedroom Echo Dot'
  - platform: vizio
    host: !secret vizio_ip
    access_token: !secret vizio_auth_token

# Log to get Spotify aliases
logger:
  default: warning
  logs:
    homeassistant.components.media_player.spotify: info

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
