homeassistant:
  customize: !include customize.yaml

# Add default configuration
default_config:

# Enables Hass IO UI
hassio:

# Discover some devices automatically
discovery:
  ignore:
    - google_cast
    - homekit
    - yamaha
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - input_boolean.k_present
      - input_boolean.m_present
      - automation.remove_new_devices_notification

# Alexa Smart Home Skill
api:

alexa:
  smart_home:
    filter:
      include_domains:
        - switch
        - script
      exclude_entities:
        - script.base_off
        - script.nighttime
        - script.spotify_switch
        - script.standby
        - script.sonos_group
        - script.sonos_ungroup
        - script.sonos_set_controller
        - switch.if_11pm_home_then_home
        - switch.if_5_30am_home_then_standby
        - switch.if_anyone_arrives_then_standby
        - switch.if_last_person_leaves_then_away
        - switch.kitchen_light
      exclude_domains:
        - automation

# iOS
ios:
  push:
    categories:
      - name: garage_trigger
        identifier: 'garage'
        actions:
          - identifier: 'GARAGE_CLOSE'
            title: 'Close Garage'
            authenticationRequired: no
            destructive: no

# Input booleans
input_boolean:
  guests_visiting:
    name: Guest Room Guests
    icon: mdi:account-multiple
  sleeping:
    name: Sleeping boolean
    icon: mdi:sleep
  k_present:
    name: K Home, Homekit
    icon: mdi:account
  m_present:
    name: M Home, Homekit
    icon: mdi:account
  x_present:
    name: Any Home, Homekit
    icon: mdi:account
  show_printer:
    name: Show Printer Info
    icon: mdi:printer

# Input Select
input_select:
  music_controller:
    name: Music Controller
    options:
      - bedroom
      - kitchen
      - living_room

# Counter for muting Guest Room Stereo
counter:
  mute_counter:
    initial: 0
    step: 1
    minimum: 0
    maximum: 2

# Binary sensors
binary_sensor:
  # K present
  - platform: template
    sensors:
      k_present:
        friendly_name: "K Home"
        value_template: >-
          {{ is_state('input_boolean.k_present','on') or 
             is_state('device_tracker.k_iphone','home') }}
      m_present:
        friendly_name: "M Home"
        value_template: >-
          {{ is_state('input_boolean.m_present','on') or 
             is_state('device_tracker.m_iphone','home') }}
      unlocked_closed:
        friendly_name: "Front Door Unlocked and Closed"
        value_template: >-
          {{ is_state('lock.home_door_lock','unlocked') and 
             is_state('binary_sensor.front_door','off') }}

# Sensors
sensor:
  # Hue custom component (installed in config/custom_components/huesensor/)
  - platform: huesensor
  # Weather prediction
  # - platform: yr
  # Spotify source
  - platform: template
    sensors:
      spotify_source:
        value_template: '{{ state_attr("media_player.spotify", "source") }}'
        friendly_name: 'Spotify Source'
      living_room_volume:
        value_template: '{{ state_attr("media_player.living_room", "volume_level") | float }}'
        friendly_name: 'Living Room Volume'
      bedroom_volume:
        value_template: '{{ state_attr("media_player.bedroom", "volume_level") | float }}'
        friendly_name: 'Bedroom Volume'
      kitchen_volume:
        value_template: '{{ state_attr("media_player.kitchen", "volume_level") | float }}'
        friendly_name: 'Kitchen Volume'
      guest_room_volume:
        value_template: '{{ state_attr("media_player.guest_room_stereo_main", "volume_level") | float }}'
        friendly_name: 'Guest Room Volume'

# Device Tracker
device_tracker:
  - platform: netgear
    password: !secret netgear_password
    devices:
      - !secret m_mac
      - !secret k_mac
    new_device_defaults:
      track_new_devices: false
    interval_seconds: 30
    consider_home: 3:00

light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.kailin_s_lamp
      - light.meghan_s_lamp
  - platform: group
    name: Living Room Lights
    entities:
      - light.elephant_lamp
      - light.gold_lamp
  - platform: group
    name: Guest Room Lights
    entities:
      - light.guest_room_light_1
      - light.guest_room_light_2
  - platform: group
    name: Basement Lights
    entities:
      - light.basement_light_1
      - light.basement_light_2
  - platform: group
    name: Front Door Light
    entities:
      - light.porch_lamp

# HomeKit
homekit:
  #auto_start: False
  filter:
    include_domains:
      - cover
      - media_player
      - light
      - switch
      - script
      - input_boolean
      - input_number
      - lock
    exclude_entities:
      - light.backyard
      - light.porch_lamp
      - media_player.spotify
      # - media_player.vizio_smartcast
      - script.close_garage
      - script.lock_if_closed_1
      - script.base_off
      - script.nighttime
      - script.spotify_switch
      - script.sonos_group
      - script.sonos_ungroup
      - script.sonos_move
      - script.sonos_group_if_playing
      - script.sonos_move_if_playing
      - script.sonos_set_controller
      - script.sonos_check_controller
      - input_boolean.k_entered
      - input_boolean.m_entered
      - input_boolean.show_printer
      - script.lock_if_closed
      - switch.if_11pm_home_then_home
      - switch.if_5_30am_home_then_standby
      - switch.if_anyone_arrives_then_standby
      - switch.if_last_person_leaves_then_away
  entity_config:
    input_boolean.k_present:
      name: "K Home"
    input_boolean.m_present:
      name: "M Home"
    media_player.living_room:
      feature_list:
        - feature: play_pause
    media_player.kitchen:
      feature_list:
        - feature: play_pause
    media_player.bedroom:
      feature_list:
        - feature: play_pause
    media_player.guest_room_stereo_main:
      name: "Guest Room Stereo"
      feature_list:
        - feature: on_off

# Yamaha
media_player:
  - platform: yamaha_musiccast
    host: !secret gr_stereo_ip
    port: !secret gr_stereo_port

# Spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
    # aliases:
    #   !secret lr_stereo_alias: 'Living Room Stereo'
    #   !secret br_stereo_alias: 'Bedroom Stereo'
    #   !secret gr_stereo_alias: 'Guest Room Stereo'
    #   !secret ki_stereo_alias: 'Kitchen Stereo'
    #   !secret ba_stereo_alias: 'Basement Stereo'
    #   !secret lr_dot_alias: 'Living Room Echo Dot'
    #   !secret ki_dot_alias: 'Kitchen Echo Dot'
    #   !secret br_dot_alias: 'Bedroom Echo Dot'

# MyQ
# cover:
#   - platform: myq
#     username: !secret myq_user
#     password: !secret myq_password

# Log to get Spotify aliases
logger:
  default: warning
  logs:
    homeassistant.components.media_player.spotify: info

sonos:
  media_player:
    advertise_addr: !secret sonos_advertise_addr

# hue:
#   bridges:
#     - host: !secret hue_ip
#       allow_hue_groups: false

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
